### ISSUE TITLE
Sportnet app error Check you log for more information 

### ISSUE THREAD

**Issue by Hollier** [micahg/plugin.video.snnow#14]
Hi there, 

I install the app on my PC and Andriod device and get the same error on both. 

Here is the Kodi Log

`   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "C:\Users\m_hol\AppData\Roaming\Kodi\addons\plugin.video.snnow\default.py", line 166, in <module>
                                                createMainMenu()
                                              File "C:\Users\m_hol\AppData\Roaming\Kodi\addons\plugin.video.snnow\default.py", line 49, in createMainMenu
                                                channels = sn.getChannels()
                                              File "C:\Users\m_hol\AppData\Roaming\Kodi\addons\plugin.video.snnow\snnow.py", line 205, in getChannels
                                                abbr = channel_map[chan_id]
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
22:40:23.763 T:2560   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.snnow/
22:40:23.763 T:2560   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.snnow/) `failed``

Could you please fix this issue.

Thanks

**Comment by micahg** [comment]
No, sorry, I don't think I'll be fixing it.

Right now the streams can't be played in Kodi.

**Comment by Hollier** [comment]
Ok thanks for looking to it.
