### ISSUE TITLE
Traceback on python 2.7.3

### ISSUE THREAD

**Issue by adamm** [micahg/plugin.video.snnow#7]
After installing this plugin on my Raspberry Pi running OpenElec 6.0.3 (Kodi 15.2) I never could get it to run.  Each attempt would throw an exception in kodi.log:

```
Traceback (most recent call last):
  File "/storage/.kodi/addons/plugin.video.snnow/default.py", line 157, in <module>
    createMainMenu()
  File "/storage/.kodi/addons/plugin.video.snnow/default.py", line 60, in createMainMenu
    keys = guide.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
```

I tried running test.py on openelec shell (python 2.7.3) it would return a similar error:

```
()
Traceback (most recent call last):
  File "./test.py", line 39, in <module>
    prog = guide[str(channel['id'])]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

But when I run test.py on my laptop (python 2.7.8), it authorizes and I get a media URL.

I am not a python expert, but I wouldn't imagine that Dictionaries have changed much between 2.7.3 and 2.7.8 to break compatibility.

**Comment by adamm** [comment]
BTW, I am running master @ 263a07e.  Thanks!
